### ISSUE TITLE
Empty SNV matrix, DB creation

### ISSUE THREAD

**Issue by mherold1** [compmetagen/strainest#13]
Hello, 
thanks for providing the tool, so far I am testing it for campylobacter strains.
I was able to run the tool with the docker container for a reduced database that I built (just selecting 10 reference strains). I then looked into building an actual database and this is where I am stuck right now.
I clustered mash-distances of ~3500 reference strains reducing them to around 650 species-specific representatives (for clusters that are not diverigng too much within MLST profiles).
The mapgenomes step works (it takes a while and creates a 1.1G MR.fasta file), but then when I run `strainest map2snp SR.fa MR.fasta snp.dgrp`, the step runs through in 2 minutes without an error but the file `snp.dgrp` just contains the header with the genome names.

How can I trace what is going wrong here?
Is this amount of genomes simply too many?

I also asked a related question on biostars:
https://www.biostars.org/p/430412/

Thanks for your feedback.

**Comment by mherold1** [comment]
I had included genomes with low coverage and MR.fasta in the previous step resulting in no overlapping "core regions".

**Comment by cirodri1** [comment]
Dear @mherold1 ,

I am also trying to build my own database and I would greatly appreciate your help on getting there...

Background information:
I have created synthetic communities with 16 bifidobacteria isolates from different species and now I am trying to analyze the metagenomic sequence data.

So far I am following the instructions given in the Methods section of the paper, I have:

1. Used the draft genomes of my 16 bifidobacteria strains to run the Mash pairwise distances as follows:
$ mash sketch -o sketch bifido1.fast bifido2.fasta bifido3.fasta ....
- I obtained a sketch.msh file

2. Used the sketch.msh file to create the distance file with Mash software as follows:
$ mash dist -t sketch.msh sketch.msh>mash.dist
- I obtained a mash.dist file

At this step, I do not know how to proceed. The Methods section continues by saying "A complete linkage hierarchical clustering using the distances computed in the previous step was then performed using a threshold between 0.001 and 0.006 for the different species..." 
- What is this complete linkage processing mean? 
- What software did you use to perform it? I found that [scipy.cluster](https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.linkage.html) can do something that seems close to what it is being asked.

"The representative genomes for the SNV profiling (Fig. 1a) defined in the previous step (R1, R2,…) were aligned against the SR using MUMmer..."
- I am unsure what is the SR (sequence representative) file needed to run MUMmer, Do I need to have a single fasta file with all my database genomes?

For the next step it seems I need the fasta files of my metagenomes and then some files called "SR.fasta" and "MR.fasta" to run the code below:
$ strainest mapgenomes R1.fasta R1.fasta… SR.fasta MR.fasta
- I am unsure what files are needed here, what are the "SR.fasta" and "MR.fasta" files composed of?

I am sorry for my confusion, but basically after Mash software I am a bit lost on what steps and files are needed to complete the database successfully. I would greatly appreciate any guidance you can provide me with in the steps that follow. Thank you!

**Comment by mherold1** [comment]
@cirodri1  
sorry I just saw this question now... If it is still up to date after a year I can also provide some more details.

At 16 genomes you probably can skip this preliminary mash step altogether. 
The mash step before strainest database construction is used to reduce the number of genomes reasonably and exclude potential outliers, e.g. genomes actually belonging to a different species. This you could spot with mash distances. 
I used R for clustering/visualizing the distances. 
You could also use a different approach, e.g. if your reference genomes are already classified in sequence types, use 1 representative of each ST or some other way of clustering (e.g. poppunk.readthedocs.io/). 

The SR sequence is one representative genome you align your other references against, in my case I used the typestrain of the species of interest. 
MR.fasta is the output (alignment) generated from the mapgenomes step

**Comment by sahilrishav2** [comment]
hello @mherold1, how did you solve this? Kindly help me too. This is my issue:

https://github.com/compmetagen/strainest/issues/20
