### ISSUE TITLE
Insufficient number of positions covered (<2)

### ISSUE THREAD

**Issue by SithWijesinghe** [compmetagen/strainest#14]
Hi,
I've been trying to run strainest using the pre-built database for E coli. But I keep getting the same error message in the title.

I generated the bowtie2 index of the map_align.fasta provided, then ran the code as in the readme, using the snv.txt file as the snp matrix. 

`bowtie2 --very-fast --no-unal -p $THREADS --mm -x $BOWTIE_DB -1 $READ1 -2 $READ2 -S ${SAMPLE}.sam`

`samtools view -b ${SAMPLE}.sam | samtools sort -o ${SAMPLE}.sorted.bam`

`samtools index ${SAMPLE}.sorted.bam`

`strainest est $SNPMATRIX ${SAMPLE}.sorted.bam $OUTDIR -t $THREADS`

The only output I get from strainest est is this.
`Insufficient number of positions covered (<2)`

Any idea as to what it might be?

Thank you in advance.

**Comment by claudiodonati** [comment]
Hi,
this message means that your reads are not aligning on the bowtie database in the positions where there are SNVs. 
Could you share the .sam file from the bowtie alignment and the snv file?

**Comment by SithWijesinghe** [comment]
Hi Dr. Donati,
Thank you for getting back to me.
Since the earlier post, I also tried aligning the same dataset with another pre-built database (for S. epidermidis) and got the same error message. So I suspect it might be the way I handled the database.
I downloaded the reference databases from ftp://ftp.fmach.it/metagenomics/strainest/ref2/. I used the `map_align.fasta` to generate the bowtie index with `bowtie2-build map_align.fasta ecoli`, then map the reads to that. And I used the `snv.txt` file as the snv matrix in strainest est.
the .sam files from alignment to e. coli and s. epidermidis indexes are here. 
[samfiles.zip.zip](https://github.com/compmetagen/strainest/files/4699606/samfiles.zip.zip)

**Comment by claudiodonati** [comment]
The error message you got means that there are no SNV positions covered by your reads in the alignment. I have looked at the sam files you provided, and it looks like that they contain very few reads (12930 for E. coli and 7054 for S epidermidis). This is a very small number, considering the size of the genomes of E.coli and S. epidermidis. Are you sure that your sample contains these two organisms? Strainest will identify the strain(s) if a sufficient number of reads can be aligned against the reference genomes, that does not seem to be the case in your data.

**Comment by SithWijesinghe** [comment]
Thank you! After looking at genus level abundance using Kraken, I found that the abundance in half my samples including the ones I tried first were lower than 1%. The other half I managed to run successfully.
