### ISSUE TITLE
Help with reference preperation

### ISSUE THREAD

**Issue by sanpande** [compmetagen/strainest#16]
Hi, I am having difficulty preparing a custom database. Is this tool still being maintained?

I downloaded the reference data from  ftp://ftp.fmach.it/metagenomics/strainest/ref2/ but, I don't see the bowtie database. I did not see any instruction on how to get from these file to the ones similar to the reference used in the tutorial: ftp://ftp.fmach.it/metagenomics/strainest/ref/pacnes.tar.gz

Thanks.
sp

**Comment by claudiodonati** [comment]
Dear Sanpande,
the tool is still maintained, and we are working on implementing new
features to automatise the whole workflow.

Regarding your question, the aligned sequences for the reference database
are in the file map_align.fasta. From this file, the user should build the
bowtie2 database. The command is

bowtie2-build [options]* <reference_in> <bt2_base>

see the bowtie2 manual for details

http://bowtie-bio.sourceforge.net/bowtie2/manual.shtml#the-bowtie2-build-indexer

Let me know if you have any problem.
Best regards

Claudio

**Comment by sanpande** [comment]
This was helpful. I got the reference and alignments. Now, how can I get snp_clust.dgrp for the following command for one of these species?

strainest est P_acnes/snp_clust.dgrp reads.sorted.bam outputdir

Thank you.
sp

**Comment by claudiodonati** [comment]
Dear Sanpande,

we renamed the files for the second version of the databases. The
snp_clust.dgrp file corresponds to the snv.txt file in the new version.
Both are comma separated tables with a list of SNVs for the different
strains. Sorry for the confusion, we should update the documentation

Claudio

**Comment by sanpande** [comment]
Hi, any suggestion on this error: Insufficient number of positions covered (<2)(strainest)

**Comment by davidealbanese** [comment]
Hi @sanpande,
see #14.
