### ISSUE TITLE
ftp link to download reference databases is broken

### ISSUE THREAD

**Issue by alipirani88** [compmetagen/strainest#17]
Hi,

Is the ftp link to download reference databases broken? I am not able to connect to ftp server - ftp.fmach.it with any of these  links - 

ftp://ftp.fmach.it/metagenomics/strainest/ref2/
ftp://ftp.fmach.it/metagenomics/strainest/ref/pacnes.tar.gz

Thanks,

**Comment by davidealbanese** [comment]
Dear @alipirani88, the issue should be fixed now.

**Comment by snitkin-lab** [comment]
@davidealbanese Thanks for the quick response. Its working.
