### ISSUE TITLE
Need help in generating snp.dgrp file

### ISSUE THREAD

**Issue by sahilrishav2** [compmetagen/strainest#20]
Hi,

I am trying to generate `snp.dgrp` file but the generated file is empty. I have 830 fasta sequence files of Pseudomonas syringae and this is the command that I used: 
```
strainest mapgenomes *.fna GCA_018394375.1_ASM1839437v1_genomic.fna mapped.fna
strainest map2snp GCA_018394375.1_ASM1839437v1_genomic.fna mapped.fna snp.dgrp
```
this is the `snp.drp` file that is empty:

>CP074578.1,Ref,GCA_000012245.1_ASM1224v1_genomic.fna,GCA_000145785.1_ASM14578v1_genomic.fna,GCA_000145805.1_ASM14580v1_genomic.fna

but the same command I used for another bacterial sequences such as Sinorhizobium medicae that contain 214 fasta sequence files work and generate `snp.dgrp` file like this:

> VITA01000001.1,Ref,GCA_000017145.1_ASM1714v1_genomic.fna,GCA_000372345.1_ASM37234v1_genomic.fna
> 331,C,C,C,T,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,T,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,C,T,C,C

Kindly help me regarding this concern.

**Comment by mherold1** [comment]
Dear Sahilrishav,
SNPs will only be called for regions that can be aligned across all references. If you have many reference genomes, there is a chance that you  have no regions aligning across all. It may also be  the case that outlier genomes introducing many gaps ruin your alignment. 
To check for those and regions of low alignment coverage in general, I adapted some code from the map2snp script to check. Let me know if  needed, then I can send you the commands. 
You should also check for snp.dgrp file e.g. if the number of SNPs is sufficient to produce meaningful results.

**Comment by sahilrishav2** [comment]
Yes, please send me the commands

**Comment by sahilrishav2** [comment]
@mherold1 , i have only one reference genome that is `GCA_018394375.1_ASM1839437v1_genomic.fna` which i am mapping with other genomes of bacteria using this command `strainest mapgenomes *.fna GCA_018394375.1_ASM1839437v1_genomic.fna mapped.fna`

**Comment by sahilrishav2** [comment]
@mherold1 , please help me. It's urgent.

**Comment by mherold1** [comment]
By reference genomes I meant all genomes you use as input. 

I used this script to check alignment coverages for the genomes:
https://git.list.lu/malte.herold/campylomics_pipeline/-/blob/master/auxiliary_scripts/check_MR_coverage.py?ref_type=heads
If the link doesn't work:
```
import csv
import click
import numpy as np
from Bio import SeqIO
from Bio.SeqIO.FastaIO import SimpleFastaParser
import sys

#mapped_fn ="MR.fasta"
mapped_fn = sys.argv[1]
#reference_fn = "../SR.fasta"
reference_fn = sys.argv[2]

reference_record = SeqIO.parse(reference_fn, 'fasta').next()
reference_seq = reference_record.seq.upper()
reference_seq_len = len(reference_seq)

mapped_handle = open(mapped_fn, 'rb')

seqn = 0
coverage = np.zeros(reference_seq_len, dtype=np.int)

for record in SimpleFastaParser(mapped_handle):
	mapped_seq_arr = np.asarray(list(record[1]))
	coverage += (mapped_seq_arr != '-')
	count = np.count_nonzero(mapped_seq_arr != '-')
	print record[0] + "\t" + str(count)
	seqn += 1
```

then sorted the resulting list and inspected/removed genomes with low coverage
```
conda activate strainest
python check_MR_coverage.py MR.fasta SR.fasta > MR_coverage.txt

sort -nr -k2 MR_coverage.txt
```

**Comment by sahilrishav2** [comment]
Thank you for your response, i will check this. Thank you once again.

**Comment by mherold1** [comment]
I forgot to add, this is how I generated the strainest database then, maybe it is also helpful:
https://git.list.lu/malte.herold/campylomics_pipeline/-/tree/master?ref_type=heads#preparing-the-strainest-database

**Comment by sahilrishav2** [comment]
Ok, thank you for your valuable time and help

**Comment by sahilrishav2** [comment]
Thank you, now, I resolved the issue. Actually, I had three genome sequences with zero coverage. After removing them, it works now.
