### ISSUE TITLE
Draft genome as reference genome

### ISSUE THREAD

**Issue by palomo11** [compmetagen/strainest#6]
Hi,

I was gonna run: 

```
strainest mapgenome genome1.fna genome2.fna reference.fna mapped.fna
```
including 20 draft genomes and my reference genome which is also a draft genome (it has 45 contigs). In --help it says:

"Align one or more genomes to a reference genome. Only the first sequence
  in the reference genome is considered. Input and output files must be in
  FASTA format."

I understand that it is gonna use only the first contig of my reference genome, isn't it? 
If that is the case, is there any way to use all the contigs? Or do I have to join my contigs and manually include some NNN in between? 

What would you recommend me?

Thank you very much in advance.

**Comment by davidealbanese** [comment]
Dear @palomo11,
yes, at the moment strainest considers for the reference genome only the first contig. Regarding the query genomes (i.e. genome1.fna, genome2.fna...) all the contigs are used. So, I suggest to merge the contigs in the reference including a reasonable number of Ns (e.g 32).

Davide

**Comment by palomo11** [comment]
OK. Thanks for the suggestion.
