### ISSUE TITLE
No compatible genomes available

### ISSUE THREAD

**Issue by palomo11** [compmetagen/strainest#7]
Hi,

I have been trying to run strainest but I having some issues. Here I explain what I have done so far:

I have 24 samples. I recovered more than 100 draft genomes from those samples. I'm interested in 10 of them. For each of this representative draft genomes I also have around 5-15 related draft genomes.
I created I database following the steps in the paper and the advices given in the other question I asked in github about how to create a reference database.

Then I followed the rest of the steps (mapgenomes, mapping, sorting, and so on...). And finally I run strainest est ... for each clust.dgrp and each sort.bam file.

The problem is that in all the abund.txt file each "strain" for each sample has 0.0 value.

In the error file it says:

```
No compatible genomes available. No compatible genomes available. No compatible genomes available...
```
In one case, it also says:
```
/home/people/name/.local/lib/python2.7/site-packages/scipy/stats/stats.py:3003: RuntimeWarning: invalid value encountered in double_scalars
  r = r_num / r_den
```

The other files look like:

counts.txt:

genomeA_sample_1_counts.txt
```
Pos	A	C	G	T
11539	0	11	0	2
11790	0	0	7	0
11916	0	0	4	0
12458	0	5	0	0
```
genomeC_sample_4_counts.txt
```
Pos	A	C	G	T
842	25	0	0	0
860	13	8	0	0
928	0	0	8	0
929	0	0	0	8
```

max_ident.txt:

```
OTU   sample2_genomeE_sort.bam
genomeE1.fa 0.661305
genomeE2.fa 0.488562
genomeE3.fa 0.515173
genomeE4.fa 0.492763
genomeE5.fa 0.628793
genomeE6.fa 0.479861
genomeE7.fa 0.533466
genomeE8.fa 0.492381
genomeE9.fa 0.479224
genomeE10.fa 0.473707
genomeE11.fa 0.534655
```

```
OTU   sample12_genomeG_sort.bam
genomeG1.fa 0.494239
genomeG2.fa 0.486111
genomeG3.fa 0.485082
genomeG4.fa 0.505453
genomeG5.fa 0.628189
genomeG6.fa 0.489712
genomeG7.fa 0.466872
genomeG8.fa 0.454938
genomeG9.fa 0.484465
genomeG10.fa 0.488066
genomeG11.fa 0.507716
genomeG12.fa 0.476132
```

here several info.txt
```
Filename	MinDepth	MaxDepth	NPos	NGen	Alpha	MSEAve	MSEStd	NLassoIter	R	PVal
sample15_genomeC_sort.bam	2.0	52.0	39443	1	0.024818219956205072	0.14995312845727451	0.0006160129318127253	2	nan	1.0

Filename	MinDepth	MaxDepth	NPos	NGen	Alpha	MSEAve	MSEStd	NLassoIter	R	PVal
sample2_genomeF_sort.bam	1.0	13.0	26640	0	nan	nan	nan	nan	nan	nan

Filename	MinDepth	MaxDepth	NPos	NGen	Alpha	MSEAve	MSEStd	NLassoIter	R	PVal
sample23_genomeAsort.bam	1.0	19.0	27382	0	nan	nan	nan	nan	nan	nan

Filename	MinDepth	MaxDepth	NPos	NGen	Alpha	MSEAve	MSEStd	NLassoIter	R	PVal
sample4_genomeB_sort.bam	1.0	32.0	24019	0	nan	nan	nan	nan	nan	nan

Filename	MinDepth	MaxDepth	NPos	NGen	Alpha	MSEAve	MSEStd	NLassoIter	R	PVal
sample13_genomeD_sort.bam	1.0	30.0	3911	0	nan	nan	nan	nan	nan	nan

Filename	MinDepth	MaxDepth	NPos	NGen	Alpha	MSEAve	MSEStd	NLassoIter	R	PVal
sample6_genomeH_sort.bam	1.0	42.0	19963	0	nan	nan	nan	nan	nan	nan
```

Do you have any idea about why I'm not getting any value in the abund.txt files?

Thank you very much in advance.

**Comment by claudiodonati** [comment]
Dear palomo11,

it looks from your data that the algorithm did not find any reference genome that is compatible with the SNVs pattern that is found by realigning the reads. Basically, strainest tries to reproduce the SNVs pattern found by aligning the reads using a linear superposition of reference genomes with Lasso penalty to guarantee sparsity. As a preliminary step, it selects for the modelling steps only reference genomes that are 95% compatible (i.e. do not differ in more than 95% of the sites) with the SNVs pattern found in the reads. By compatible we mean that if in position X you have 10% A and 90% T, a reference genome that is compatible in that position has either a A or a T.

From your data, it looks like you reference genomes are very distant from your SNP patterns. In the file max_ident.txt you find, for each reference genome, 
genomeE1.fa 
genomeE2.fa 
...

the fraction of position that are compatible with the SNV pattern in that sample. This number is in one example in the range 0.4-0.7, which is very low. For this reason strainest immediately stops. Only for sample sample15_genomeC_sort.bam strainest tries to fit something, but only does 2 lasso iterations and does not a good job in reproducing the data.

So, the question is: how did you choose the reference genomes? If you assembled them from the metagenomic reads themselves, it is kind of strange that they look so distant when you realign the reads on them.

Hope this helps
